name: Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Analysis
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        depths: [10, 12, 14, 16]
        boards: ["rocw"]
      # Ensure all matrix jobs are reported, even if one fails
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        
    - name: Build project
      run: |
        chmod +x build.sh
        ./build.sh || echo "Compilation error"
        
    - name: Verify binary exists
      run: test -f baeagn || (echo "Binary not found" && exit 1)
      
    - name: Install binary
      run: sudo install -m 0755 baeagn /usr/local/bin
      
    - name: Check for benchmark script
      run: test -f bench.sh || (echo "Benchmark script not found" && exit 1)

    - name: Run benchmarks
      run: if true; then ./bench.sh $BOARD ${{ matrix.depths }}; fi
      env:
        BOARD: ${{ matrix.boards }}
        DEPTH: ${{ matrix.depths }}
