name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Benchmark
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        depths: [12, 16, 20, 24, 32, 64, 192]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        
    - name: Build project
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Verify binary exists
      run: test -f baeagn || (echo "Binary not found" && exit 1)
      
    - name: Install binary
      run: sudo install -m 0755 baeagn /usr/local/bin
      
    - name: Check for benchmark script
      run: test -f bench.sh || (echo "Benchmark script not found" && exit 1)

    - name: Run benchmarks
      run: ./bench.sh $BOARD ${{ matrix.depths }}
      env:
        BOARD: "quiw"
        DEPTH: ${{ matrix.depths }}