name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: ./build.sh
        
    - name: Install binary
      run: sudo install -m 0755 baeagn /usr/local/bin
      
    - name: Run benchmark
      run: baeagn "r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3" 9 > $HOME/bench_results/bench.log
      
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: $HOME/bench_results/bench.log