name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Verify binary exists
      run: test -f baeagn || (echo "Binary not found" && exit 1)
      
    - name: Install binary
      run: sudo install -m 0755 baeagn /usr/local/bin
      
    - name: Run benchmark
      run: |
        LOG=$HOME/bench_results/bench.log
        mkdir -p $HOME/bench_results
        baeagn "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3" 253 > $LOG & pid=$!
        while ! grep -q "^Best variation: Bf1b5" $LOG; do true; done
        pkill -term baeagn
        cat $LOG

