name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Verify binary exists
      run: test -f baeagn || (echo "Binary not found" && exit 1)
      
    - name: Install binary
      run: sudo install -m 0755 baeagn /usr/local/bin
      
    - name: Run benchmark
      run: test -f bench.sh || (echo "Script not found" && exit 1)

    - name: Depth 20
      run: ./bench.sh quiw 20

    - name: Depth 24
      run: ./bench.sh quiw 24   

    - name: Depth 32
      run: ./bench.sh quiw 32

    - name: Depth 64
      run: ./bench.sh quiw 64
 